name: dstll-diff-web

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  PATTERN: '**.go'

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: 'dhth/hours'
          path: 'hours/hours'
          fetch-depth: 20

      - name: Get starting commit
        id: get-starting-commit
        working-directory: ./hours/hours
        run: |
          echo "commit=$(git rev-parse --short HEAD~10)" >> $GITHUB_OUTPUT

      - name: Get ending commit
        id: get-ending-commit
        working-directory: ./hours/hours
        run: |
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - id: get-dstll-diff
        uses: dhth/dstll-action-test@v0.1.12
        with:
          directory: hours/hours
          pattern: '**.go'
          starting-commit: ${{ steps.get-starting-commit.outputs.commit }}
          ending-commit: ${{ steps.get-ending-commit.outputs.commit }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install diff2html-cli
        run: |
          npm install -g diff2html-cli

      - name: Generate webpage
        env:
          DIFF: ${{ steps.get-dstll-diff.outputs.diff }}
        run: |
          mkdir -p docs
          echo "$DIFF" | diff2html --input stdin --title "dstlled-diff ${{ steps.get-starting-commit.outputs.commit }}..${{ steps.get-ending-commit.outputs.commit }} -- ${PATTERN}" --file docs/index.html
          cat docs/index.html
