name: dstll-test-caller

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: dhth/dstll-action-test@v0.1.3
        with:
          pattern: '**.go'
      - run: echo "$DIFF"
        env:
          DIFF: ${{ steps.foo.outputs.diff }}
